language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_install:
  - git submodule update --init --recursive

script:
  - cargo build --verbose
  - cargo build --verbose --manifest-path=examples/xmp-sys/Cargo.toml
